services:

  # db:
  #   image: postgres
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=
  #     - POSTGRES_DATABASES=keycloak,mynvr
  #     - POSTGRES_HOST_AUTH_METHOD=trust
  #   volumes:
  #     - ./docker/postgres:/docker-entrypoint-initdb.d

  # idp:
  #   image: quay.io/keycloak/keycloak
  #   command: start-dev
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - KEYCLOAK_ADMIN=admin
  #     - KEYCLOAK_ADMIN_PASSWORD=admin
  #     - KC_DB=postgres
  #     - KC_DB_URL=jdbc:postgresql://db/keycloak
  #     - KC_DB_USERNAME=postgres
  #     - KC_DB_PASSWORD=

  mediamtx:
    image: bluenviron/mediamtx
    ports:
      - 8888:8888
      - 8889:8889
    volumes:
      - ./docker/mediamtx/config.yml:/mediamtx.yml
      - ./data:/data

  agent:
    build: .
    ports:
      - 4000:4000
    environment:
      - PORT=4000
      - RECORDING_DIR=/data/recordings        # As seen from mediamtx
      - MEDIAMTX_API=http://mediamtx:9997     # As seen from agent
      - MEDIAMTX_RTSP=rtsp://mediamtx:8554    # As seen from agent
      - MEDIAMTX_HLS=http://localhost:8888    # As seen from external
      - MEDIAMTX_WEBRTC=http://localhost:8889 # As seen from external
      - STORAGE_CLASS=json-file
      - STORAGE_DIR=/data                     # As seen from agent
    volumes:
      - ./data:/data
