services:

  db:
    image: postgres

  idp:
    image: quay.io/keycloak/keycloak
    command: start-dev
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin

  mediamtx:
    image: bluenviron/mediamtx
    volumes:
      - ./docker/mediamtx/config.yml:/mediamtx.yml
      - ./data:/data

  agent:
    build: .
    ports:
      - 4000:4000
    environment:
      - PORT=4000
      - STORAGE_DIR=/data
    volumes:
      - ./data:/data
