services:

  db:
    image: postgres

  idp:
    image: quay.io/keycloak/keycloak
    command: start-dev
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin

  agent:
    build: component/agent
    ports:
      - 4000:4000
    environment:
      - PORT=4000
